### ISSUE TITLE
How could we allow the developer to style the board?

### ISSUE THREAD

**Issue by lourenci** [lourenci/react-kanban#141]

**Comment by GLuchtenberg** [comment]
Well, we can have something like "laneClasses", but that seems pretty ugly, maybe having a @flow or typescript type, and give the users the capabilities to pass a Lane Component to the board, what do you think?

**Comment by bofeiw** [comment]
My workaround is to write vanilla css and import it. 
If you inspect the element, you will find that these lanes and card have same classes. 
For example I'm building a scheduler based on this library and need to style it nicely.
Here are some of the css that works for me:

*Note class names might be different from machine to machine bcause the class names look like very random*

```css
.sc-VigVT {
    /*  timetable wrapper  */
    width: 100%;
}

.sc-VigVT,
.sc-VigVT * {
    box-sizing: border-box !important;
}

.sc-jTzLTM {
    /*  timetable  */
    width: 100%;
    display: grid;
    grid-template-columns: auto auto auto;
    grid-gap: 10px;
    padding: 10px;
}

.sc-htpNat:first-child {
    /*  staging area  */
    grid-column: 1/4;

}

.sc-htpNat {
    /*  card inside timetable  */
    margin: 0;
}
```
